version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - .data:/data
    container_name: "docker-mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test
volumes:
  data: {}

networks:
  default:
    name: mongodb_network